"""Specific configurations for the CARTE paper."""


carte_datalist = ['anime_planet',
 'babies_r_us',
 'beer_ratings',
 'bikedekho',
 'bikewale',
 'buy_buy_baby',
 'cardekho',
 'chocolate_bar_ratings',
 'clear_corpus',
 'coffee_ratings',
 'company_employees',
 'employee_remuneration',
 'employee_salaries',
 'fifa22_players',
 'filmtv_movies',
 'journal_jcr',
 'journal_sjr',
 'jp_anime',
 'k_drama',
 'michelin',
 'mlds_salaries',
 'movies',
 'museums',
 'mydramalist',
 'nba_draft',
 'prescription_drugs',
 'ramen_ratings',
 'roger_ebert',
 'rotten_tomatoes',
 'spotify',
 'us_accidents_counts',
 'us_accidents_severity',
 'us_presidential',
 'used_cars_24',
 'used_cars_benz_italy',
 'used_cars_dot_com',
 'used_cars_pakistan',
 'used_cars_saudi_arabia',
 'videogame_sales',
 'whisky',
 'wikiliq_beer',
 'wikiliq_spirit',
 'wina_pl',
 'wine_dot_com_prices',
 'wine_dot_com_ratings',
 'wine_enthusiasts_prices',
 'wine_enthusiasts_ratings',
 'wine_vivino_price',
 'wine_vivino_rating',
 'yelp',
 'zomato']


carte_singletable_baselines = ['carte-gnn',
 'catboost',
 'sentence-llm-concat-num_histgb',
 'sentence-llm-concat-num_xgb',
 'sentence-llm-embed-num_histgb',
 'sentence-llm-embed-num_xgb',
 'tablevectorizer-fasttext_histgb',
 'tablevectorizer-fasttext_xgb',
 'tablevectorizer-llm_histgb',
 'tablevectorizer-llm_xgb',
 'tablevectorizer_histgb',
 'tablevectorizer_logistic',
 'tablevectorizer_mlp',
 'tablevectorizer_randomforest',
 'tablevectorizer_resnet',
 'tablevectorizer_ridge',
 'tablevectorizer_xgb',
 'tablevectorizer_tabpfn',
 'target-encoder_histgb',
 'target-encoder_logistic',
 'target-encoder_mlp',
 'target-encoder_randomforest',
 'target-encoder_resnet',
 'target-encoder_ridge',
 'target-encoder_xgb',
 'target-encoder_tabpfn',
 ]

carte_multitable_baselines = [
        "original_carte-multitable",
        "matched_carte-multitable",
        "original_catboost-multitable",
        "matched_catboost-multitable",
        "original-sentence-llm_histgb-multitable",
        "matched-sentence-llm_histgb-multitable",
]